const productList = [
  {
    title: "Skolebolle",
    productType: "Bakegods",
    price: "50kr",
    allergies: ["hvete"],
    ingredients: "Hvetemel, smør, sukker",
    imagePath: "/assets/images/products/skolebolle.jpg",
  },
  {
    title: "Flettaloff",
    productType: "Bakegods",
    price: "50kr",
    allergies: ["hvete"],
    ingredients: "Hvetemel, smør, sukker",
    imagePath: "/assets/images/products/flettaloff.jpg",
  },
  {
    title: "Surdeigbrød",
    productType: "Bakegods",
    price: "60kr",
    allergies: ["hvete", "rug"],
    ingredients: "Hvetemel, surdeigsstarter, vann, salt",
    imagePath: "/assets/images/products/surdeigbrod.jpg",
  },
  {
    title: "Rugbrød",
    productType: "Bakegods",
    price: "55kr",
    allergies: ["rug"],
    ingredients: "Rugmel, hvetemel, vann, salt",
    imagePath: "/assets/images/products/rugbrod.jpg",
  },
  {
    title: "Fiberbrød",
    productType: "Bakegods",
    price: "60kr",
    allergies: ["hvete"],
    ingredients: "Hvetemel, havremel, linfrø, sesamfrø",
    imagePath: "/assets/images/products/fiberbrod.jpg",
  },
  {
    title: "Kornbrød",
    productType: "Bakegods",
    price: "50kr",
    allergies: ["hvete"],
    ingredients: "Hvetemel, havregryn, solsikkefrø, linfrø",
    imagePath: "/assets/images/products/kornbrod.jpg",
  },
  {
    title: "Golrotbrød",
    productType: "Bakegods",
    price: "55kr",
    allergies: ["hvete"],
    ingredients: "Hvetemel, gulrot, melk, smør",
    imagePath: "/assets/images/products/golrotbrod.jpg",
  },
  {
    title: "Seterbrød",
    productType: "Bakegods",
    price: "50kr",
    allergies: ["hvete"],
    ingredients: "Hvetemel, melk, smør, salt",
    imagePath: "/assets/images/products/seterbrod.jpg",
  },
  {
    title: "Havrebrød",
    productType: "Bakegods",
    price: "55kr",
    allergies: ["havre"],
    ingredients: "Havremel, hvetemel, vann, salt",
    imagePath: "/assets/images/products/havrebrod.jpg",
  },
  {
    title: "Kornsputer",
    productType: "Bakegods",
    price: "50kr",
    allergies: ["hvete"],
    ingredients: "Hvetemel, sukker, smør, havregryn",
    imagePath: "/assets/images/products/kornsputer.jpg",
  },
  {
    title: "Kanelbolle",
    productType: "Bakegods",
    price: "45kr",
    allergies: ["hvete"],
    ingredients: "Hvetemel, smør, sukker, kanel",
    imagePath: "/assets/images/products/kanelbolle.jpg",
  },
  {
    title: "Skolebolle",
    productType: "Bakegods",
    price: "50kr",
    allergies: ["hvete"],
    ingredients: "Hvetemel, smør, sukker",
    imagePath: "/assets/images/products/skolebolle.jpg",
  },
  {
    title: "Winderbrød",
    productType: "Bakegods",
    price: "60kr",
    allergies: ["hvete"],
    ingredients: "Hvetemel, smør, sukker",
    imagePath: "/assets/images/products/winderbrod.jpg",
  },
  {
    title: "Vaniljebolle",
    productType: "Bakegods",
    price: "50kr",
    allergies: ["hvete"],
    ingredients: "Hvetemel, sukker, vanilje",
    imagePath: "/assets/images/products/vaniljebolle.jpg",
  },
  {
    title: "Kardemommebolle",
    productType: "Bakegods",
    price: "50kr",
    allergies: ["hvete"],
    ingredients: "Hvetemel, sukker, kardemomme",
    imagePath: "/assets/images/products/kardemommebolle.jpg",
  },
  {
    title: "Hvetebolle",
    productType: "Bakegods",
    price: "45kr",
    allergies: ["hvete"],
    ingredients: "Hvetemel, smør, sukker",
    imagePath: "/assets/images/products/hvetebolle.jpg",
  },
  {
    title: "Rosinbolle",
    productType: "Bakegods",
    price: "50kr",
    allergies: ["hvete", "rosiner"],
    ingredients: "Hvetemel, rosiner, smør",
    imagePath: "/assets/images/products/rosinbolle.jpg",
  },
  {
    title: "Winderstang",
    productType: "Bakegods",
    price: "55kr",
    allergies: ["hvete"],
    ingredients: "Hvetemel, smør, sukker",
    imagePath: "/assets/images/products/winderstang.jpg",
  },
  {
    title: "Kremboller",
    productType: "Bakegods",
    price: "60kr",
    allergies: ["hvete"],
    ingredients: "Hvetemel, fløte, sukker",
    imagePath: "/assets/images/products/kremboller.jpg",
  },
  {
    title: "Svart kaffe",
    productType: "Drikke",
    price: "66kr",
    allergies: [],
    ingredients: "Kaffe",
    imagePath: "/assets/images/products/svartkaffe.jpg",
    isWarm: true,
  },
  {
    title: "Café au Lait",
    productType: "Drikke",
    price: "70kr",
    allergies: ["melk"],
    ingredients: "Kaffe, melk",
    imagePath: "/assets/images/products/cafeaulait.jpg",
    isWarm: true,
  },
  {
    title: "Cappuccino",
    productType: "Drikke",
    price: "75kr",
    allergies: ["melk"],
    ingredients: "Espresso, steamet melk, melkeskum",
    imagePath: "/assets/images/products/cappuccino.jpg",
    isWarm: true,
  },
  {
    title: "Varm Mørk Sjokolade",
    productType: "Drikke",
    price: "80kr",
    allergies: ["melk"],
    ingredients: "Mørk sjokolade, melk, sukker",
    imagePath: "/assets/images/products/varmmorksjokolade.jpg",
    isWarm: true,
  },
  {
    title: "Varm Sjokolade",
    productType: "Drikke",
    price: "75kr",
    allergies: ["melk"],
    ingredients: "Kakao, melk, sukker",
    imagePath: "/assets/images/products/varmsjokolade.jpg",
    isWarm: true,
  },
  {
    title: "Chai te",
    productType: "Drikke",
    price: "65kr",
    allergies: ["melk"],
    ingredients: "Svart te, krydder, melk, honning",
    imagePath: "/assets/images/products/chaite.jpg",
    isWarm: true,
  },
  {
    title: "Issjokolade",
    productType: "Drikke",
    price: "85kr",
    allergies: ["melk"],
    ingredients: "Kakao, melk, sukker, isbiter",
    imagePath: "/assets/images/products/issjokolade.jpg",
    isWarm: false,
  },
  {
    title: "Kaffeshakes",
    productType: "Drikke",
    price: "90kr",
    allergies: ["melk"],
    ingredients: "Kaffe, melk, sukker, isbiter",
    imagePath: "/assets/images/products/kaffeshakes.jpg",
    isWarm: false,
  },
  {
    title: "Sorbéshakes",
    productType: "Drikke",
    price: "85kr",
    allergies: [],
    ingredients: "Fruktpuré, juice, isbiter",
    imagePath: "/assets/images/products/sorbeshakes.jpg",
    isWarm: false,
  },
];

export default productList;
